GeoulCore: pkg.sh 없애고 load-package로 대체함.
 * 패키지 설정에서 필요한 값만 읽어들여서 셸 변수 정의로 출력해주는 load-package 만듬.
 * . pkg.sh를 load-package로 대체하고 관련 변수 이름들도 따라 바꿔줌.

 * pkg.sh에서 lock 관련 부분을 추출하여 lockproc으로 만들고 대체시킴.

 * geoul-sync finish 내용 밖으로 뺌.

 * for-each-packages 셸 함수에 대해서도 동작하게 손 봄.
 * set -u로 의도치 않은 변수 사용 방지함.



git-svn-id: svn+ssh://project.sparcs.org/project/geoul/svn@402 8166199e-f512-0410-aa90-bfaab4d738d9

diff --git a/geoul/trunk/src/sync/geoul-sync/main b/geoul/trunk/src/sync/geoul-sync/main
--- a/geoul/trunk/src/sync/geoul-sync/main
+++ b/geoul/trunk/src/sync/geoul-sync/main
@@ -6,7 +6,6 @@
 # Written by Jaeho Shin <netj@sparcs.org>.
 # (C) 2006-2009, Geoul Project. (http://project.sparcs.org/geoul)
 
-
 ## printers
 usage() {
     local exitcode=$?
@@ -36,9 +35,12 @@ die() {
 err() { die "$@" >&2; }
 
 
+
+script=$1; shift
+
 ## read package information
-cd "$(dirname "$0")"
-. /mirror/lib/pkg.sh
+cd "`dirname "$script"`"
+eval `load-package pkg name source frequency syncInProgress`
 
 
 ## choose what to do
@@ -64,15 +66,15 @@ export GETARGS="$@"
 
 ## stop
 if [ "$triggered" = stop ]; then
-    if sync_in_progress; then
-        kill_lock_owner
+    if $syncInProgress; then
+        lockproc lock kill
         die 0 "stopped running sync"
     else
         ruins=`find lock lock.* log log.* 2>/dev/null || true`
         if [ -n "$ruins" ]; then
             # TODO: clean up (as in finish)
             rm -f log log.*
-            release_lock
+            lockproc lock clean
             die 0 "cleaned up dead sync"
         else
             die 4 "no sync in progress"
@@ -81,8 +83,8 @@ if [ "$triggered" = stop ]; then
 fi
 
 
-## jobs to be/not to be done while sync_in_progress
-if sync_in_progress; then
+## jobs to be/not to be done while sync is in progress
+if $syncInProgress; then
     case "$triggered" in
         watch)
         exec tail -f log
@@ -100,22 +102,24 @@ fi
 
 
 ## check timestamp if regular sync
-compute_times # defines: timepast interval failures penalty delay remaining
+eval `load-package timePastSecs intervalSecs numFailures penaltySecs delaySecs`
 if [ "$triggered" = regularly ]; then
     desc=
-    if [ $penalty -gt 0 ]; then
-        desc="=`iso-interval $interval`+`iso-interval $penalty`(${failures} failures)"
+    if [ $penaltySecs -gt 0 ]; then
+        desc="=`iso-interval $intervalSecs`+`iso-interval $penaltySecs`(${numFailures} failures)"
     fi
-    if [ $timepast -lt $delay ]; then
-        die 8 "not yet (age=`iso-interval $timepast` < `iso-interval $delay`$desc)"
+    if [ $timePastSecs -lt $delaySecs ]; then
+        die 8 "not yet (age=`iso-interval $timePastSecs` < `iso-interval $delaySecs`$desc)"
     else
-        msg "old enough (age = `iso-interval $timepast` >= `iso-interval $delay`$desc)"
+        msg "old enough (age = `iso-interval $timePastSecs` >= `iso-interval $delaySecs`$desc)"
     fi
 fi
 
 
+# FIXME use synchronized
+
 ## lock this package
-acquire_lock || die 4 "locked or another sync in progress"
+lockproc lock grab || die 4 "locked or another sync in progress"
 
 
 ## prepare logging and unlocking
@@ -134,49 +138,10 @@ fi
 # backup stdout/err fd's and redirect everything to log
 exec 3>&1- 4>&2-  >>$log 2>&1
 
+# TODO remove this trap
 finish() {
     trap '' EXIT ERR INT HUP TERM
     set +e
-    local result=
-    if [ $exitcode -eq 0 ]; then
-        # record success
-        result=success
-        touch timestamp
-        clear_failures
-    else
-        # record failure
-        result=failure
-        increase_failures
-    fi
-    msg "sync $result at `humandate`"
-    # stop monitoring log
-    if [ -n "$tailpid" ]; then
-        sleep 1
-        kill $tailpid 2>/dev/null
-        wait $tailpid
-    fi
-    # restore stdout/err
-    exec >&3- 2>&4-
-    # save log
-    #  compress log
-    gzip -f $log
-    ln -sf $log.gz .$result.log.gz
-    rm -f log log.*
-    #  mark success/failure
-    case "$result" in
-        failure)
-        # raise need-to-report flag
-        touch failed.needsreport
-        # TODO: check sources, switch sources
-        ;;
-        success)
-        ;;
-    esac
-    #  record to RSS
-    record-news.feed sync-$result $log.gz
-    #  TODO record-sync-cost using `collect-sync-cost $log.gz`
-    release_lock
-    exit $exitcode
 }
 trap 'exitcode=$?; set +x; finish' EXIT ERR
 trap 'exit 2' INT HUP TERM
@@ -191,7 +156,54 @@ cat <<EOF
 + node=$HOSTNAME
 + triggered=$triggered
 + frequency=$frequency
-+ timepast=`iso-interval $timepast`
-+ failures=$failures
++ timepast=`iso-interval $timePastSecs`
++ failures=$numFailures
 EOF
-set +e -x
+
+# run script
+bash -x "$script"
+exitcode=$?
+
+result=
+if [ $exitcode -eq 0 ]; then
+    # record success
+    result=success
+    touch timestamp
+    rm -f failed
+else
+    # record failure
+    result=failure
+    eval `load-package numFailures`
+    # TODO: use lower bound?
+    echo $(($numFailures + 1)) >failed
+fi
+msg "sync $result at `humandate`"
+# stop monitoring log
+if [ -n "$tailpid" ]; then
+    sleep 1
+    kill $tailpid 2>/dev/null
+    wait $tailpid
+fi
+# restore stdout/err
+exec >&3- 2>&4-
+# save log
+#  compress log
+gzip -f $log
+ln -sf $log.gz .$result.log.gz
+rm -f log log.*
+#  mark success/failure
+case "$result" in
+    failure)
+    # raise need-to-report flag
+    touch failed.needsreport
+    # TODO: check sources, switch sources
+    ;;
+    success)
+    ;;
+esac
+#  record to RSS
+record-news.feed sync-$result $log.gz
+#  TODO record-sync-cost using `collect-sync-cost $log.gz`
+lockproc lock release
+
+exit $exitcode
